### ISSUE TITLE
Example in readme is broken

### ISSUE THREAD

**Issue by anentropic** [flash-oss/medici#28]
trying this example:
```js
const startDate = moment().subtract("months", 1).toDate(); // One month ago
const endDate = new Date(); // today

const transactions = await myBook.ledger({
  account: "Income",
  start_date: startDate,
  end_date: endDate
});
```
I get:
```
CastError: Cast to date failed for value "Invalid Date" at path "datetime" for model "Medici_Transaction"
    at model.Query.exec (/Users/anentropic/Documents/Dev/Work/balance-demo/node_modules/mongoose/lib/query.js:4437:21)
    at Book.ledger (/Users/anentropic/Documents/Dev/Work/balance-demo/node_modules/medici/src/book.js:212:30)
    at main (/Users/anentropic/Documents/Dev/Work/balance-demo/pay_periods.js:32:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  messageFormat: undefined,
  stringValue: '"Invalid Date"',
  kind: 'date',
  value: Invalid Date,
  path: 'datetime',
  reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

    assert.ok(!isNaN(value.valueOf()))

      at castDate (/Users/anentropic/Documents/Dev/Work/balance-demo/node_modules/mongoose/lib/cast/date.js:13:12)
```
Same if I use `Date` for both with no moment.js stuff.

It turns out the fix is to pass `start_date` and `end_date` as strings instead of `Date` instances, i.e.:
```js
  const transactions = await myBook.ledger({
    account: "Income",
    start_date: "2021-01-01T12:00:00",
    end_date: "2021-05-01T08:00:00"
  });
  console.log(transactions);
```
...works fine.

This is with `medici-4.0.1` `mongoose-5.12.7` and MongoDB 4.2

**Comment by koresar** [comment]
Thank you very much! Fixed in medici v4.0.2
